-- =============================================================
-- TUKLAS — Barangay Seed Data
-- All 134 official barangays of Baguio City
-- Source: Philippine Statistics Authority (PSA)
-- =============================================================
-- Run AFTER schema.sql
-- Safe to re-run: ON CONFLICT DO NOTHING skips duplicates
-- =============================================================

INSERT INTO barangays (name) VALUES
  ('Abanao-Zandueta-Kayong-Chugum-Otek'),
  ('Alfonso Tabora'),
  ('Ambiong'),
  ('Andres Bonifacio'),
  ('Asin Road'),
  ('Atok Trail'),
  ('Aurora Hill North Central'),
  ('Aurora Hill Proper'),
  ('Aurora Hill South Central'),
  ('Bagong Lipunan'),
  ('Bakakeng Central'),
  ('Bakakeng North'),
  ('Bal-Marcoville'),
  ('Balsigan'),
  ('Banao-Kristong Hari'),
  ('Bayan Park East'),
  ('Bayan Park Village'),
  ('Bayan Park West'),
  ('BGH Compound'),
  ('Brookside'),
  ('Brookspoint'),
  ('Cabinet Hill-Teacher''s Camp'),
  ('Camdas Subdivision'),
  ('Camp 7'),
  ('Camp 8'),
  ('Camp Allen'),
  ('Campo Filipino'),
  ('City Camp Central'),
  ('City Camp Proper'),
  ('Country Club Village'),
  ('Cresencia Village'),
  ('Dagsian Lower'),
  ('Dagsian Upper'),
  ('Dizon Subdivision'),
  ('Dominican Hill-Mirador'),
  ('Dontogan'),
  ('DPS Area'),
  ('Engineers Hill'),
  ('Fairview Village'),
  ('Ferdinand'),
  ('Fort del Pilar'),
  ('Gabriela Silang'),
  ('General Luna Road'),
  ('Gibraltar'),
  ('Greenwater Village'),
  ('Guisad Central'),
  ('Guisad Sorong'),
  ('Happy Hollow'),
  ('Happy Homes-Campo Sioco'),
  ('Harrison Road Central'),
  ('Holy Ghost Extension'),
  ('Holy Ghost Proper'),
  ('Honeymoon (Honeymoon Road)'),
  ('House of Providence'),
  ('Imelda R. Marcos'),
  ('Imelda Village'),
  ('Irisan'),
  ('Kabayanihan'),
  ('Kagitingan'),
  ('Kayang Extension'),
  ('Kayang-Hilltop'),
  ('Kias'),
  ('Legarda-Burnham-Kisad'),
  ('Loakan Proper'),
  ('Lopez Jaena'),
  ('Lourdes Subdivision Extension'),
  ('Lourdes Subdivision Proper'),
  ('Lower Dagsian'),
  ('Lower Magsaysay'),
  ('Lower Rock Quarry'),
  ('Lualhati'),
  ('Lucnab'),
  ('Magsaysay Lower'),
  ('Magsaysay Private Road'),
  ('Magsaysay Upper'),
  ('Malcolm Square-Perfecto'),
  ('Manuel A. Roxas'),
  ('Market Subdivision Upper'),
  ('Middle Quezon Hill'),
  ('Middle Rock Quarry'),
  ('Military Cut-off'),
  ('Mines View Park'),
  ('Modern Site East'),
  ('Modern Site West'),
  ('MRR-Queen of Peace'),
  ('Naguilian Road'),
  ('New Lucban'),
  ('Outlook Drive'),
  ('Pacdal'),
  ('Padre Burgos'),
  ('Padre Zamora'),
  ('Palma-Urbano'),
  ('Pinsao Pilot Project'),
  ('Pinsao Proper'),
  ('Poliwes'),
  ('Pucsusan'),
  ('Quezon Hill Proper'),
  ('Quezon Hill Upper'),
  ('Quirino Hill East'),
  ('Quirino Hill Lower'),
  ('Quirino Hill Middle'),
  ('Quirino Hill West'),
  ('Quirino-Magsaysay-Prieto-Dizon'),
  ('Rizal Monument Area'),
  ('Rock Quarry Lower'),
  ('Rock Quarry Middle'),
  ('Rock Quarry Upper'),
  ('Roxas-Trinidad-Montilla'),
  ('Sagpat'),
  ('Saint Joseph Village'),
  ('Salud Mitra'),
  ('San Antonio Village'),
  ('San Luis Village'),
  ('San Roque Village'),
  ('San Vicente'),
  ('Sanitary Camp North'),
  ('Sanitary Camp South'),
  ('Santa Escolastica'),
  ('Santo Rosario'),
  ('Santo Tomas Proper'),
  ('Santo Tomas School Area'),
  ('Scout Barrio'),
  ('Session Road Area'),
  ('Slaughter House Area'),
  ('SLU-SVP Housing Village'),
  ('South Drive'),
  ('Teodora Alonzo'),
  ('Trancoville'),
  ('Upper Dagsian'),
  ('Upper Magsaysay'),
  ('Upper Market Subdivision'),
  ('Upper QM'),
  ('Upper Rock Quarry'),
  ('Victoria Village')
ON CONFLICT (name) DO NOTHING;

-- Verify count
-- SELECT COUNT(*) FROM barangays;  -- expected: 134
